# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generated.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'generated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerated.proto\"O\n\x0bLedCommands\x12\x14\n\x0c\x62rightness_1\x18\x01 \x01(\r\x12\x14\n\x0c\x62rightness_2\x18\x02 \x01(\r\x12\x14\n\x0c\x62rightness_3\x18\x03 \x01(\r\"5\n\x0c\x41htTelemetry\x12\x13\n\x0btemperature\x18\x01 \x01(\r\x12\x10\n\x08humidity\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEDCOMMANDS']._serialized_start=19
  _globals['_LEDCOMMANDS']._serialized_end=98
  _globals['_AHTTELEMETRY']._serialized_start=100
  _globals['_AHTTELEMETRY']._serialized_end=153
# @@protoc_insertion_point(module_scope)
